# config/application.yml
defaults: &defaults
  mail_key: ''
  mail_domain: ''
  hire: "Deep Work"
  #hire: "I am available for hire."
  encryption_key: ""
  admin:
    email: 
    pwd: xxx

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
