# config/application.yml
defaults: &defaults
  admin:
    email: mr.huangwenwei
    pwd: hww8773084123

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
