# config/application.yml
defaults: &defaults
  hire: "Currently I'm available for hire."
  mail_key: 'xxxx'
  mail_domain: 'xxx'
  admin:
    email: xxx@gmail.com
    pwd: xxx

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
